@startuml

'面接管理システム'

actor 面接官

rectangle 面接 {

    rectangle 今回のスコープ {
        面接官 --> (面接を登録する)
        面接官 --> (面接のステータスを進める)
        (面接のステータスを進める) --> (面接官を設定する)
    }
    面接官 --> (会議を予約する)

}


@enduml