@startuml


object 採用ポジション {
    採用ポジションID
    採用ポジション名
    募集ステータス
}

object 面接 {
    面接ID
    応募日
    進捗ステータス
}
note right: \
              ・応募日: 面接登録した日付 \
            \n・必ずポジションが1つ紐づく


object 面接記録 {
    面接ID
    面接官ID
    面接種別
    面接日付
    面接結果
}
note right: \
              ・種別は「1次面接」「2次面接」「最終面接」\
            \n・面接結果は「合格」「不合格」

object 面接官 {
    面接官ID
    名前
}


採用ポジション "1" <-l-  "0..n" 面接

面接 "1" *--- "0..n" 面接記録

面接記録 "1" -- "1..n" 面接官


@enduml