@startuml


object 採用ポジション {
    採用ポジションID
    採用ポジション名
    募集ステータス
}
note top: ステータスは「募集中」「募集終了」


object 採用選考 {
    応募日
    進捗ステータス
    候補者情報
    採用ポジションID
}
note right: \
              ・応募日: 面接登録した日付 \
            \n・必ずポジションが1つ紐づく

object 面接 {
    面接日付
    面接種別
    面接結果
}
note right: \
              ・面接結果は「未評価」「合格」「不合格」 \
            \n・選考ステータスが「選考中」以外のときには設定できない \
            \n・面接字数は1からインクリメントされる \
            \n・面接日は過去日を設定できない



object 面接官 {
    面接官ID
    名前
}


採用ポジション "1" <-l-  "0..n" 採用選考

採用選考 "1" *--- "0..n" 面接

面接 "1" -- "1..n" 面接官


@enduml