@startuml

rectangle 採用ポジション集約 {

    object "採用ポジション\n<集約ルート>" as 採用ポジション {
        採用ポジションID
        採用ポジション名
        募集ステータス
    }
}
note left: ステータスは「募集中」「募集終了」


rectangle 採用選考集約{

    object "採用選考\n<集約ルート>" as 採用選考 {
        応募日
        進捗ステータス
        候補者情報
        採用ポジションID
    }
    note top: \
                  ・選考ステータスは「未応募」「選考中」「採用」「不採用」 \
                \n・面談から始める場合、\n\t初期ステータスは「未応募」\n\t応募日はブランク(のちに選考に進んだ日付が応募日になる) \
                \n・面接から始める場合、\n\t初期ステータスは「選考中」\n\t応募日は登録日


    object 面談 {
        面談日付
        面談担当者ID
    }
    note top: ・面談は選考開始〜狩猟の間に2回まで設定できる



    object 面接 {
        面接日付
        面接種別
        面接結果
        面談担当者ID
    }
    note bottom: \
                  ・面接結果は「未評価」「合格」「不合格」 \
                \n・選考ステータスが「選考中」以外のときには設定できない \
                \n・面接字数は1からインクリメントされる \

}

rectangle 採用担当者集約 {
    object "採用担当者\n<集約ルート>" as 採用担当者 {
        担当者ID
        名前
    }
}


採用ポジション "0..1" <--  "0..n" 採用選考

採用選考 "1" *-- "0..n" 面接
採用選考 "1" *-- "0..n" 面談

面談 --> 採用担当者
面接 --> 採用担当者


@enduml