@startuml
object 部 {
    部ID
    名前
    承認状態
}
note right : \
    部活動の単位組織を表す(野球部、ダンス部など)。\
    \n・承認状態は、最初は「未承認」である。\
    \n・部員が5名以上所属かつ学校の承認が通ると「承認済み」となる。\
    \n・部員が4名以下になると、承認状態は「未承認」に戻る



object 部員 {
    部ID
    生徒ID
}

object 生徒 {
    生徒ID
    名前
}



部   "1"    *-d-  "0..n" 部員
部員 "0..n" --> "1"    生徒

@enduml

