@startuml

object ユーザ {
    ユーザID
    ユーザ名
    }
note right: ・ユーザ名は3文字以上20文字以下


object サークル {
    サークルID
    サークル名
    オーナー
    メンバー
}
note right: \
             ・サークル名は3文字以上20文字以下 \
           \n・サークル名はすべてのサークルで重複しない \
           \n・サークルに所属するユーザの最大数はサークルのオーナーとなるユーザを含めて30名まで


@enduml
